### ISSUE TITLE
Some links do not work in documentation

### ISSUE THREAD

**Issue by albertas** [iodide-project/pyodide#1257]
These links are not working in the [documentation homepage](https://pyodide.readthedocs.io/en/latest/):
- https://pyodide.readthedocs.io/en/latest/pypi.html
- https://pyodide.readthedocs.io/en/latest/new-packages.html  (should be updated to https://pyodide.readthedocs.io/en/latest/development/new-packages.html)

Maybe tests could be added to check for dead links. I think [Sphinx supports this type of checks](https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-the-linkcheck-builder).

**Comment by rth** [comment]
Thanks for the report @albertas ! Yes, we should have used [linking via sphinx](https://www.sphinx-doc.org/en/1.5/markup/inline.html#cross-referencing-syntax) with e.g
```
:ref:`micropip`
```
rather than manually providing the URL. The corresponding section label already exists [here](https://github.com/iodide-project/pyodide/blame/master/docs/usage/loading-packages.md#L54). As far as I can tell those are the only two remaining occurrences of manual internal links. 

Would you be interested in making a PR to fix it?

**Comment by leafjolt** [comment]
I made a PR (#1260) fixing the two links mentioned. I apologize if I made any errors, as I have little experience working with Sphinx.
