### ISSUE TITLE
[solved] 

### ISSUE THREAD

**Issue by daoxian** [iodide-project/pyodide#1263]

**Comment by rth** [comment]
Don't erase questions, even they are solved. The idea of issues is to be useful to all contributors, and they won't be if history is not preserved. I reverted the changes.

What was the solution in this case?

**Comment by hoodmane** [comment]
The original error message `printf is not defined` is the result of attempting to use `printf` inside of `EM_JS`. Inside of `EM_JS` you have the option of using `console.log` (or I like `console.error` better since it comes with a stack trace). I am pretty sure you can also use `_printf` but that will give a lower quality result.

Outside of `EM_JS`, `printf` works as normal, though you have to be careful to make sure to include a `\n`, standard out will not be flushed until you put a `\n`. You can also do `EM_ASM(console.error("some message"););` which is particularly useful if you want to log a `JsRef` you can do `EM_ASM({ console.error("jsobj is:", Module.hiwire.get_value($0)); }, jsobj);`.

To print the repr of a Python object, you can do `PyObject_Print(pyobj, stdout, 0);` but then you have to remember to `printf("\n");` afterwards to flush stdout. As a more annoying but more flexible option, there is also:
```C
PyObject* msg = PyUnicode_FromFormat("The key was: %R and the value was: %R\n", key, value);
printf("%s", PyUnicode_AsUTF8(msg));
Py_CLEAR(msg); // or you could just leak it of course
```
