### ISSUE TITLE
Way to reference to JS from python

### ISSUE THREAD

**Issue by daoxian** [iodide-project/pyodide#1279]
@mdboom  Is there any way to reference to a JS TypedArray variable from Python now? I'm looking forward to a reference-style memoryview which shares buffer between JS and Python, instead of a copy into python, which will cause a memory leak. Because I have no idea on how to release the memoryview object after using it in python. Or could you please introduce some method  to eliminate this kind of memory leak?

**Comment by hoodmane** [comment]
I don't think there are any memory leaks caused by referencing TypedArrays from python: the TypedArray can be freed by javascript as soon as the variable referencing it from Python is deallocated. If the reference is local to a function scope, then it is guaranteed to be released as soon as the frame of that function is released (immediately if the function returns successfully, a bit less immediately if it throws an exception).

**Comment by daoxian** [comment]
Thanks and will close this thread, since no reproduce after eliminate another problem.
