### ISSUE TITLE
More refined object sharing

### ISSUE THREAD

**Issue by mdboom** [iodide-project/pyodide#13]
I'm starting to feel like the shared namespace between Python and JS creates more problems than it solves, and a more explicit way of managing this would be better.

I would propose something like (in Python):

```python
from js import window
```

and in Javascript:

```javascript
var sys = pyimport('sys')
```

The idea is that each side would have their own namespaces, which is persisted between cells (as notebook users are used to), but to get objects between the two worlds, they would have to use an import statement/function of some kind.

**Comment by bcolloran** [comment]
something like that looks right to me.

thinking ahead to the more generic case using iodide stdlib, maybe a pattern along the lines of

```
py = iodide.registerInterpreter(
    'https://iodide.io/pyodide.js',
    {cellType: "python",
        cellLabelString: "Py",
        ...[who knows what other options will go in here...]...
    }
)
var { sys } = py

R = iodide.registerInterpreter(
    'https://iodide.io/iodizer.js',
    {cellType: "R", cellLabelString: "R", ... }
)
var { glm } = R
```

anyway, just brainstorming with an eye looking down the road, but don't let this idle thought slow you down in present -- IMO better to focus on whatever implementation let's you get up and running and experimenting rather than trying to shake out the stdlib API in too much detail (of course, we can also begin discussing/implementing/experimenting with that API if you think the time is right for that).

**Comment by mdboom** [comment]
Thanks.  I think we're definitely on the same page.

I don't think getting the:

```
var { sys } = py
```

syntax to work will be easy, though, since that means we would have to put *everything* in the Python namespace on an object, just so the Javascript user could pick one thing out of it.  (If Javascript let you overload the `.` operator like Python does we could create a proxy object, but I'm not sure you can).  So I think it will look more like:

```
var sys = pyimport('sys')
```
