### ISSUE TITLE
Potential memory leak in WebLoop.py

### ISSUE THREAD

**Issue by johnwason** [iodide-project/pyodide#1325]
WebLoop.py uses `js.setTimeout` to implement call_* functions. The code is:

```
h = asyncio.Handle(callback, args, self, context=context)
setTimeout(h._run, delay * 1000)
return h
```

https://github.com/iodide-project/pyodide/blob/de7c3420103fabbf01c589fcf2a429d157a6bd5e/src/pyodide-py/pyodide/webloop.py#L139

I think this may result in a memory leak, since the `h._run` JS proxy is never released.

**Comment by hoodmane** [comment]
Yes, that's a memory leak. Thanks for the report. (There's currently a bunch of these =( )

**Comment by hoodmane** [comment]
From a design perspective, I'm not sure what the best way to fix leaks like this is. We need control over the lifetime of PyProxy from Python. I think being able to create a JsProxy of a PyProxy would help a lot because then we could directly access the `destroy` api from Python. Once #1306 is merged, this will be mitigated in any browser that supports `FinalizationRegistry` (it might take a long time for the memory to be reclaimed in that way though).

**Comment by johnwason** [comment]
The simple solution is to create a JS function "pyodide_set_timeout" with the following contents:

```
function pyodide_set_timeout(handler, delay)
{
  setTimeout(function() {
    try
    {
        handler()
    }
    except (e)
    {
      handler.destroy()
      throw e
    }
  }, delay)
}

```

It may also be possible to create a wrapper function `destroy_after_call` that contains the logic above. That would require a change in how python2js works, so that it creates a special proxy for this operation.

**Comment by hoodmane** [comment]
I think `destroy_after_call` is the right choice, because we need this also in the C api to fix this leak:
https://github.com/iodide-project/pyodide/blob/fa06dc112fb076c0352e1cdec8054d4c5ed3208b/src/core/jsproxy.c#L650
I think we should add this as an API on the pyodide python package and encourage its use for this use case.

On the other hand, this only works in the simple case of a function that can be decrefed after calling once. In general, we might need to manually destroy a `PyProxy` with a more complex lifecycle from Python. For this, it would suffice to have a `create_double_proxy` API that takes a Python Object and returns a `JsProxy` of a `PyProxy` of the object. Then we can pass this to Javascript, it gets unwrapped into a `PyProxy` and when we think it's done we can call `double_proxy.destroy`. This also could be used for `removeEventListener` (see #382, the current solution to that issue causes issue #1049).

**Comment by johnwason** [comment]
It would make sense to add both. There is also a need for the ability to call toJs() and other JS proxy functions from Python. Right now I need a wrapper function to do a deep copy. I suspect there will need to be a family of helper functions for the various scenarios.

**Comment by hoodmane** [comment]
Right, the `double_proxy` should allow calling `toJs` from Python. I guess to do `to_py` from Javascript you'd need a PyProxy of a JsProxy... *sigh*
