### ISSUE TITLE
Document Python and Javascript public API 

### ISSUE THREAD

**Issue by rth** [iodide-project/pyodide#175]
Independently of the build setup, it would be nice to document the public API for the Python and Javascript interfaces. 

`src/pyodide.py` is succinct enough, so that is not too critical.

However in js, the `pyodide` object exposes a number of methods / properties,

```js
>> Object.getOwnPropertyNames(pyodide)

[..., 'allocate', 'getMemory', 'addRunDependency', 'removeRunDependency', 'then',
 'callMain', 'run', 'abort', 'noExitRuntime', 'loadPackage', 'usingWasm',
 'preloadResults', 'preloadPlugins', 'calledRun', 'stdin', 'stdout', 'stderr',
 'websocket', 'hiwire_new_value', 'hiwire_get_value', 'hiwire_decref', 'pyimport',
 'PyProxy', 'runPython', 'version', 'packages']
```

and even with the examples it may be difficult to know which ones the user might be interested in using and which ones are for internal use only. That also could be the occasion to evaluate what should be part of the public API.

For instance, iodide has some API reference in https://iodide.io/docs/api.html

For the documentation itself, one possibility could be to use sphinx: natively in Python and with [sphinx-js](https://github.com/erikrose/sphinx-js) extension to parse jsdoc formatted javascript docstrings (never tried that myself). There may be also some JS based alternative for it.

Then the question is where an eventual documentation could be deployed: in the same domain as  https://iodide.io or somewhere else..

**Comment by mdboom** [comment]
It will be difficult to limit the namespace in `pyodide` to just the public API, given the design of emscripten.  Most of these are emscripten implementation details.  (The original design of emscripten was to port whole applications, so there wasn't much consideration around namespaces).  We could add an `api` key within there and put only public things in it, though, perhaps, just to make that more obvious.  Or it might be possible to change the object that `languagePluginLoader` returns to include this object inside it, alongside only the truly public members.

The public API, such as there is, already has documentation [here](https://github.com/iodide-project/pyodide/blob/master/docs/).  I like the simple approach -- using markdown that renders decently on github -- because it's so easy to manage.  We could link to it from the README to make it more obvious...

If we did go with sphinx, we could just host it on readthedocs -- that's the easiest thing to deploy to probably.

**Comment by mdboom** [comment]
That makes sense.

Lets do this:

- [ ] Reorganize the pyodide object so that the emscripten "Module" is a private member, and only public API things are at the top-level
- [ ] Add a `doc/api_reference.md` to store reference docs for the public api.

If this grows large enough, consider a "real" documentation tool like sphinx.

I can probably work on the first bullet point above -- I think I have a reasonable idea of how it could be done.
