### ISSUE TITLE
Check packages against Pyodide ABI version

### ISSUE THREAD

**Issue by mdboom** [iodide-project/pyodide#244]
As hinted at in #241, it would be good, when loading a package, to check it against the expected ABI version of Pyodide.  Some things, like the `NUM_PARAMS` setting, do change the ABI, and it would be nice to provide a friendly error message about the mismatch rather than something seemingly very obscure.  

I haven't looked into the details, but this probably involves modifying `file_packager.py` to store the ABI in the metadata, and then checking this value within `loadPackage` at load time.  Alternatively, we could use something special in the package file naming, but that seems possibly more prone to error.

**Comment by madhur-tandon** [comment]
@mdboom Can I be assigned this perhaps?

**Comment by mdboom** [comment]
Sure!  Github won't let me officially assign a non-developer, but this note can serve as confirmation that you're working on it.  Thanks!

**Comment by hamilton** [comment]
@mdboom I believe he can be added as a community member (one of our org teams we've made) and you can assign him that way, right?

**Comment by mdboom** [comment]
Indeed.  I forgot that github has made that much better.  @madhur-tandon : Accept the invitation in your e-mail, and then I should be able to assign you.

**Comment by mdboom** [comment]
We need to define an ABI version number somewhere.  This number will be incremented (manually) whenever we break the ability to load packages built for an earlier version.  The most common cause of this is when we change the `NUM_PARAMS` value, though there might be others, like an `emscripten` version upgrade.

This version needs to get embedded somehow into the `.js` files for the packages we create (which are built by `file_packager.py`), and on loading the package we need to check that its ABI version matches the ABI version of the currently running Pyodide, and if not throw an exception about the mismatch.

Hope that helps!  Ask here or on gitter if you need further pointers.

**Comment by madhur-tandon** [comment]
@mdboom I have briefly looked at how ``buildpkg.py``works and some of the contents of ``file_packager.py``. I noticed how the output of this system is a ``.js`` file (such as ``numpy.js``).
Since the contents of this ``.js`` file is from the variable ``ret`` in the ``file_packager.py`` script, we could perhaps also accommodate the ABI version number there. Before we proceed, I have the following doubts: 

- Let's say there are 2 outputs corresponding to 2 libraries [say ``numpy.js`` and ``pandas.js``]. Should both of them share the same ABI number always? Or can it be different for both of them? Similarly, all other ``.js`` files can have different ABI numbers or not?

- Let's say an ABI number is incorporated into each of the ``.js`` files. The question is how to incorporate or specifically, where to incorporate? I looked at the ``metadata`` dictionary in the ``file_packager.py`` script as a potential choice, but then, there is the option of ``--separate_metadata`` which will create a separate file for the metadata rather than putting it in the ``.js`` file. So, do you have any ideas for a good place to put it?

- About checking this ABI number on loading the package, where should the ABI version for the ``pyodide`` project as a whole (and not the individual ``.js`` files) be defined at? Lastly, can you tell me / point me to the code where we actually call ``loadPackage`` function? I am a bit rusty with JavaScript but I am working on it.
