### ISSUE TITLE
Failed to use pyodide in a web worker

### ISSUE THREAD

**Issue by oeway** [iodide-project/pyodide#246]
I am trying to use pyodide in the web worker with `importScripts(".../pyodide.py")`, soon I noticed that it does not support it. I think it make sense to run pyodide in a seperate thread with web workers. Otherwise, the GUI may stuck for heavy computations.

Not sure exactly, but it seems to me that removing the dependencies to `window`, `document` and use `importScripts` in [pyodide.js](https://github.com/iodide-project/pyodide/blob/master/src/pyodide.js) would work.

Related to https://github.com/iodide-project/pyodide/issues/242 , I think it would be also nice to have a way to share and access the loaded packages, loaded wasm modules between different web workers. Because every web worker will download their own package files and load the wasm modules, which will consume a lot of memory and time to load.  And they may be addressed with [SharedArrayBuffers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer) and `postMessage(WebAssembly.Module)`.

**Comment by mdboom** [comment]
I totally agree this would be worthwhile work -- both to make sure we're webworker compatible (which is somewhat related to the work to make this node.js compatible), and then as a follow on to properly share as much as we can between workers.

I've been a little bogged down with other things lately, but I'm happy to help anyone who wants to take this on.

**Comment by jstafford** [comment]
@mdboom I've made a good start on this, but before I make a PR I need some guidance. 

There were basically just two changes needed to make the code work in a webworker. The first was to replace uses of window with self. The second was to replace the use of dom manipulation to load scrips with importScripts. 

The first change to switch window to self is easy, but isn't enough if you want node compatibility. I'm not sure of a way to do this correctly across node, webworkers, the browser, and the emscripten compiled code.

The second issue of switching to use importScripts was also straight forward, but I ended up with a pyodide_webworker.js since it wasn't clear to me how to preserve both paths without making a rats nest in the code. If the dual maintenance of two pyodide scripts is okay, then this is easy. If a cross browser/worker/node loader is needed, then again I'm unsure how to do it cleanly.

A third issue is testing everything in a webworker. Webworkers have a reduced api compared with the browser, and so there might be things used in python that aren't available in a webworker. I haven't really looked at your testing setup yet, but just running the tests gives me the impression it is convoluted.

Finally, I looked a little at the node compatibility PR that is open, but it's unclear to me what the status of that is.

Any thoughts/advice/guidance is welcome.

**Comment by mdboom** [comment]
Thanks for looking at this.  As I said before, I think this would be really nice to have.

> The first change to switch window to self is easy, but isn't enough if you want node compatibility.

I think it's fine to tackle webworkers now and node later.  The changes to support two environments should hopefully make supporting a third easier.

> but I ended up with a pyodide_webworker.js since it wasn't clear to me how to preserve both paths without making a rats nest in the code.

Would it be helped if you could use a templating language to separate out the main thread code paths from the WebWorker paths?  Or using some sort of babel transformation?  `pyodide.js` is already a "built" artifact (it just runs through `sed` right now), but it wouldn't be a huge step to run it through more sophisticated preprocessing.  I don't know if that would help it be less of a rat's nest having not seen it...

> A third issue is testing everything in a webworker.

The testing setup is based on selenium, running inside a (native) py.test to orchestrate things.  It should be theoretically possible to write a wrapper that loads pyodide and a test's code in a webworker and runs it there.  There seems to be some [prior art for this](https://www.reddit.com/r/javascript/comments/4yq237/how_do_you_test_service_workers/) -- but that post is about 2 years old.  The nice thing about our test setup is that we've already abstracted away the browser so we can test everything in Firefox and Chrome.  Web Workers would just be a third and fourth thing.  The hard part would just be figuring out how to automate the process of running arbitrary code in the web worker and getting the results back out the other end through selenium.  I expect, as with all things selenium, it won't be super easy.

I'd be comfortable with merging something that had a basic smoke test for web workers as a start, and we can advertise the web worker support as "experimental and largely untested", and work on proper full testing as a follow-on.

I think the node PR stalled out, but let's ping @gabrielfreire to be sure.

**Comment by gabrielfreire** [comment]
Well, my PR was basically to enable `file_package.py` generate `*.data.js` files that are `node.js` friendly.

I created this repo: https://github.com/gabrielfreire/pyodide-node with local `.data.js` and `.wasm` files to work on `Node.js` support, it comes with automated unit tests
the following is in the `README.md` as well
# Building
## Requirements
- Node v8.x +
`git clone https://github.com/gabrielfreire/pyodide-node.git`
`cd pyodide-node`
`npm install`

# Testing

`npm test`

**Comment by hoodmane** [comment]
Shouldn't this be closed now since Pyodide works quite well in workers?

**Comment by rth** [comment]
Closing as resolved. Please open new more specific issues related to web-workers. Thanks!
