### ISSUE TITLE
Update Pyodide to use the latest version of Iodide

### ISSUE THREAD

**Issue by madhur-tandon** [iodide-project/pyodide#298]
Currently, ``Pyodide`` uses a previous version of ``Iodide`` which used to have ``jupyter notebook`` type cells. However, Iodide has been updated and uses a flat text file like editor with the ``JSMD`` format.

The demo which uses the older version is here:
https://iodide.io/pyodide-demo/python.html

The demo which uses the newer version is here:
https://extremely-alpha.iodide.io/notebooks/151/

It should be possible to update ``pyodide`` so that the locally built version resembles the newer JSMD format as seen in the 2nd URL above.

**Comment by madhur-tandon** [comment]
@mdboom @hamilton I was thinking I could be assigned this. But, I would need some starter tips as well because I am not much familiar with the ``Iodide`` repository.

**Comment by mdboom** [comment]
I'm not sure this makes sense, since the standalone mode of Iodide that this takes advantage of no longer works with current versions of Iodide.  (i.e. Iodide requires a particular server setup to make the iframe work etc.)  I think a better solution would be to implement some (hand-waving) convenient way to insert a `plugin` section that would test a local version.  We definitely need some discussion on this before it will be ready for implementation.

**Comment by rth** [comment]
We are no longer including `python.html` so I think this can be closed.
