### ISSUE TITLE
matplotlib button set should be offset by left margin of plot

### ISSUE THREAD

**Issue by hamilton** [iodide-project/pyodide#304]
h/t @teonbrooks 

The new buttons look great. The buttons could have a `margin-left` that offsets the buttons by the plot's left margin width, so the buttons are aligned to the plot body.

![screen shot 2019-01-24 at 7 23 20 am](https://user-images.githubusercontent.com/95735/51701724-e9eb2c00-1fc6-11e9-995b-0d6b9783690f.png)

**Comment by teonbrooks** [comment]
also, the past default behavior of the plot used to align to the center of the body of text. currently it is aligned to the far left of the page

**Comment by madhur-tandon** [comment]
@hamilton @teonbrooks I highlighted this when I was initially working on stylising the buttons and I mentioned it in the original issue here: https://github.com/iodide-project/pyodide/issues/36

``
c) The whole widgets toolbar is not at the centre of the figure, I think it would be nice to make it at the centre. How should we approach tackling this perhaps?
``

With that said, I am glad you approve of them. Since I have already worked with them, Can I be assigned this issue too perhaps? Please let me know, Thanks!
