### ISSUE TITLE
The PDF ``button`` on the matplotlib widgets toolbar doesn't seem to work

### ISSUE THREAD

**Issue by madhur-tandon** [iodide-project/pyodide#305]
The notebook for Pyodide available here: https://extremely-alpha.iodide.io/notebooks/151/ has a demo on how to use ``matplotlib`` to plot charts. There are 3 buttons which enable the user to save the chart in various formats - ``PDF, PNG and SVG``. 

Clicking on any of these should result in a pop-up window something like this:

<img width="443" alt="screenshot 2019-01-25 at 12 37 01 pm" src="https://user-images.githubusercontent.com/20173739/51730574-fa220a80-209d-11e9-9d36-fbeac05ad909.png">

However, clicking on the ``PDF`` button does not result in a pop-up window. Instead, it embeds another chart inside the original chart something like this:

<img width="592" alt="screenshot 2019-01-25 at 12 34 13 pm" src="https://user-images.githubusercontent.com/20173739/51730609-2f2e5d00-209e-11e9-93bf-4c08be140d7e.png">

I don't think this is the desired behaviour.

**Comment by madhur-tandon** [comment]
@hamilton @mdboom Could you guys confirm if this is happening or is it just for me? If yes, what could be causing this? Can I be assigned and get some starter tips as well [if indeed this is a real issue]?

**Comment by mdboom** [comment]
This is indeed a real issue.  It turned out to be just as simple to fix as it would be to give you the starter tips, so I'll have a PR shortly.

In general, though, to investigate these sorts of issues, I rebuild with the `--profiling` flag:

`EMCC_FLAGS="--profiling" make`

Then, I can open up the Web Console and see the error and use the debugger to track it down. In this case, there was a missing symbol `__ZNSt3__28ios_base4initEPv` which indicates that C++ exception support wasn't getting compiled in.  (I believe this must have changed with the recent upgrade of emscripten).  Adding that symbol to the `EXPORTED_FUNCTIONS` list resolves the error.
