### ISSUE TITLE
Make pyproxies behave more like functions

### ISSUE THREAD

**Issue by mdboom** [iodide-project/pyodide#332]
Given this cool notebook from @gnestor:

```
%% fetch
js: //unpkg.com/react@16/umd/react.development.js
js: //unpkg.com/react-dom@16/umd/react-dom.development.js

%% py
from js import React, ReactDOM, iodide

count = 1

def handle_click(event):
    global count
    count += 1
    print(count)
    ReactDOM.render(
        counter(), 
        iodide.output.element('div')
    )
    
def counter():
    return React.createElement(
        'button', 
        {'onClick': handle_click}, 
        str(count)
    )

ReactDOM.render(
    counter(), 
    iodide.output.element('div')
)

%% py
from js import iodide

iodide
```

it fails with:

![image](https://user-images.githubusercontent.com/38294/54233212-d4808180-44e2-11e9-9373-85a2b0d1c853.png)

This is probably related to the pyproxies not duck typing as functions the way they should, but it's not clear atm given that the backtrace through react is kind of opaque.

**Comment by gnestor** [comment]
Thanks for picking up on this! And for the quick fix at https://github.com/iodide-project/pyodide/pull/333!

**Comment by hamilton** [comment]
Thanks for the wild notebook @gnestor :) React in Python does feel a bit unholy ...

**Comment by gnestor** [comment]
🤷‍♂️

**Comment by hamilton** [comment]
(in a good way!)

**Comment by hamilton** [comment]
@gnestor yes, I suspect there may be something very interesting in all this. I edited your notebook a bit so that each click doesn't add a new DOM element (going to check docs to make sure its clear what `iodide.output.element` does). Feel free to ditch my disco colors :) 

Ruminating on this a bit more, it would be interesting to see if hooks work neatly in this paradigm. I suspect that having something like this in notebooks would be powerful, and in most cases the types of components someone would be using here would be probably straightforward enough (in this case, maybe move the `counter` to a `useState` call?)

![Mar-13-2019 11-37-24](https://user-images.githubusercontent.com/95735/54305997-a99b3980-4585-11e9-9516-d80b573bb39a.gif)


```
%% fetch
js: //unpkg.com/react@16/umd/react.development.js
js: //unpkg.com/react-dom@16/umd/react-dom.development.js
%% md

# React & Python

%% py
from js import React, ReactDOM, iodide

count = 1
elem = iodide.output.element('div')

def handle_click(event):
    global count
    count += 1
    print(count)
    ReactDOM.render(
        counter(),
        elem
    )
    
def counter():
    return React.createElement(
        'button', 
        {'onClick': handle_click}, 
        str(count)
    )

ReactDOM.render(
    counter(), 
    elem
)

%% css 

.user-markdown h1 {
  text-align: center;
  font-size:40px;
  font-weight: 900;
  text-transform: uppercase;
  color: coral;
}

.side-effect-element button {
  transition: .2s;
  border: 2px solid orange;
  width: 100px;
  height:100px;
  font-size: 35px;
  font-weight:900;
  background-color: tomato;
  color: white;
  border-radius: 5px;
  display: block;
  margin:auto;
  margin-top: 100px;
}

.side-effect-element button:hover {
  border: 2px solid gray;
  box-shadow: 
    5px 5px 0px mediumorchid,
    10px 10px 0px orange,
    15px 15px 0px gold;
}

.side-effect-element button:active {
  background-color: purple;
}



%% py
from js import iodide

iodide
```

**Comment by gnestor** [comment]
@hamilton So cool to see this working. I don't see why hooks wouldn't work. I will certainly play around with this when once Iodide is updated.
