### ISSUE TITLE
matplotlib widgets are ugly

### ISSUE THREAD

**Issue by mdboom** [iodide-project/pyodide#36]
Someone with some good CSS-fu could make it look much nicer.

![image](https://user-images.githubusercontent.com/38294/40376592-b3b0b730-5dbc-11e8-9f4b-7edfcaa45a1f.png)

**Comment by madhur-tandon** [comment]
@mdboom Can I be assigned this too? Also, can I have some starter tips as well? Specifically because this seems a bit tougher as I do not know how the interactivity between the matplotlib figure and the web page works, but this surely sounds interesting!

**Comment by rth** [comment]
Thanks @madhur-tandon, feel free to take any issue that is labeled "help wanted" or "good first issue", just commenting that you plan to work could be enough.

For this issue, I would make a matplotlib figure in a notebook then look in the browser developer tool (F12 key) which CSS file the current style for widgets is coming from. Then try to improve it.

**Comment by mdboom** [comment]
I agree with @rth -- using the CSS console is the easiest way to go.  The widgets themselves are generated in the `wasm_backend.py` file, particularly in the toolbar class.  You could add one-off styles there.

**Comment by madhur-tandon** [comment]
@mdboom @rth 
I was thinking of the following style. The buttons change their color on hover. I find it elegant enough!
Does this suffice or do you guys prefer something else? Please let me know, Thanks!

![ezgif com-gif-maker](https://user-images.githubusercontent.com/20173739/50888397-94861b00-141b-11e9-8583-1df24713264e.gif)

**Comment by mdboom** [comment]
@hamilton, @bcolloran : I'd appreciate your thoughts, particularly wrt blending into Iodide.

**Comment by hamilton** [comment]
tagging @wlach here as well to get his thoughts. @madhur-tandon these look pretty good to me!

I would make sure to endeavor to use

```css
font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"; 
```

for consistency. This is the css system font stack we use elsewhere.

Overall, I like these buttons. Another approach re: styling would be to go for the [Material Design spec](https://material.io/design/components/buttons.html#outlined-button) on buttons, but frankly I think these are less heavy style-wise.

**Comment by wlach** [comment]
This looks good. I would probably go for a more subtle css transition when the buttons are hovered over, like @hamilton I find the material design transitions a bit heavy / overwhelming and would like to move away from that approach over the next few months.

**Comment by bcolloran** [comment]
@hamilton i actually think using system fonts is

**Comment by bcolloran** [comment]
oops pressed wrong buttons, ignore comment if it ended up in your email (i was going to say that i don't think we should use system fonts in general, bc doing so has resulted in some UI weirdness in iodide, but i wanted to delete the comment because I think it's actually fine for the matplotlib use case, and better than bundling fonts)

**Comment by madhur-tandon** [comment]
@mdboom @hamilton @bcolloran @wlach The style that I showed above was a concept and I tried implementing it. However, I am unable to stimulate the ``change colour on hover effect``. For some reason, the events ``mouseenter`` and ``mouseleave`` do not work. I am planning on experimenting with other events such as ``mouseover`` and ``mouseout`` and maybe will try some other hacks too.

For now, this is what it looks like 
``[haven't used the System Fonts (the ones suggested by @hamilton) for now as I was just experimenting]``

<img width="983" alt="screenshot 2019-01-12 at 7 06 22 pm" src="https://user-images.githubusercontent.com/20173739/51073934-bee70b00-169d-11e9-9df0-1d89833793bd.png">

I want to ask few things though:

a) Is it even possible to add the ``colour change on hover effect``? particularly because this is a bit different from how we do it the standard way!
b) If I am not able to do it, would it be fine to let it be as it is? [aka just the grey buttons?]
c) The whole widgets toolbar is not at the centre of the figure, I think it would be nice to make it at the centre. How should we approach tackling this perhaps?

**Comment by hamilton** [comment]
@madhur-tandon it's hard to say how to proceed here without seeing any code. Can you put what you have in a PR so I can comment on it?

Re: the button effect, did you try using the CSS `:hover` selector on those buttons? One approach would be something like this:

```css

button.matplotlib-buttons {
     background-color: gainsboro;
    transition: 100ms;
}

button.matplotlib-buttons:hover {
  background-color: gray;
}

```

I haven't actually checked to see if those colors work, but that should be the general principle. adding `transition: 100ms` allows CSS to do the heavy lifting.

**Comment by madhur-tandon** [comment]
@hamilton I have added the code in the PR submitted here: https://github.com/iodide-project/pyodide/pull/296

As told by @mdboom, I have added styles and changed the DOM through python in the ``wasm_backend.py`` file.

I understand the ``:hover`` selector. In fact, this is what I used when I built a quick HTML + CSS style GIF that I attached earlier to showcase what I will be going to implement. However, I don't think we can use it as we are adding the styles through HTML DOM Elements and HTML DOM Events through Python which is different from using the ``:hover`` selector in a ``.css`` file. Here, to simulate the ``:hover`` selector, I used the events ``mouseenter`` and ``mouseleave``. Another option can be to use ``mouseover`` and ``mouseout``. For now, I do not know if we can really use the ``:hover`` selector as I do not know which ``CSS`` file is generated after ``matplotlib`` is built. Could you now take a look at it perhaps?

Again, the main issue is that the effect of ``colour change on hover`` does not occur and the background remains as it is. Please let me know, Thanks!

**Comment by madhur-tandon** [comment]
@hamilton : UPDATE

I have been able to fix the above mentioned issue. It turns out I was using the callbacks incorrectly. This can be seen in the PR https://github.com/iodide-project/pyodide/pull/296 in the updated comments there. A GIF as a proof is also attached there. Please let me know, Thanks!

**Comment by bcolloran** [comment]
looks nice @madhur-tandon :-)
