### ISSUE TITLE
Scipy package size impacts loading time

### ISSUE THREAD

**Issue by xhlulu** [iodide-project/pyodide#386]
Is there any reason why scipy takes so much space to load?

I've tried out creating a simple pyodide app that uses Scikit-learn for classification: https://alpha.iodide.io/notebooks/1836/?viewMode=report

The app takes roughly a minute and half to load. Network profiling in Chrome seems to indicate that one of the major cause is `scipy.data`, which takes roughly 67 MB to load (on my network, that is roughly 20 seconds to download the entire package). Here's a picture of the results:

![Capture](https://user-images.githubusercontent.com/21180505/56388061-08427b80-61f4-11e9-83f9-d6515b7f2e86.PNG)

In comparison, `scikit-learn.data` and `numpy.data` are roughly 4 MBs each. Furthermore, it seems that `scipy.data` cannot be cached either.

Thank you in advance!

**Comment by rth** [comment]
It's due to LAPACK being statically linked in scipy (see https://github.com/iodide-project/pyodide/issues/240). Switching to dynamic linking should reduce the package size significantly.

**Comment by mdboom** [comment]
Yes.  Also try Firefox.  On Chrome, we are forced to load all `.so`'s up front, where as Firefox only loads the ones you need.

**Comment by xhlulu** [comment]
Thanks for the heads up! I think that certain algorithms will use scipy, but that's good to know for the ones that don't.

**Comment by rth** [comment]
> What sort of approach could I apply to save this network cost after the initial loading (and caching)? [..] So far I haven't found any resource for increasing browser caching size limit so I'd love to receive some pointer on that.

At least in firefox you can increase the maximum size of cached files by typing `about:config`, then searching and setting,
```
browser.cache.disk.max_entry_size   100000   (default value was 51200)
```
There appear to be some heuristic on how the total cache size is computed, so I might be OK. Otherwise you can always increase it manually,
```
browser.cache.disk.smart_size.enabled    false
browser.cache.disk.capacity  1000000  (default was 256000)
```
Though it looks like `browser.cache.disk.capacity` was already at 1GB for some users, in which case there is probably no need to change it.


> E.g. break down the file into chunks that are cacheable (e.g. scipy.data.1,...,scipy.data.5), or increase Firefox's cache?

Ideally we should break it by submodule (e.g. `scipy.sparse`, `scipy.linalg`, etc) but it would require some work figuring out dependencies.

**Comment by joemarshall** [comment]
I think once clapack is dynamically linked, that will so massively reduce the size that no-one will care, it adds 5mb to most of the so files in scipy which adds up to a massive amount.

I am really quite close to building scipy with the ultra strict function signature things that upstream wasm requires. Once that is working, I can't see that lapack as a dynamic library would be hard, because there'll no longer be multiple different signatures (typically 3) for the same lapack calls which is most of what breaks clapack dynamic linking i think.

**Comment by rth** [comment]
Absolutely, that would be the ideal solution. I was just suggesting a workaround in the meantime / for previous release.

**Comment by xhlulu** [comment]
> `browser.cache.disk.max_entry_size   100000   (default value was 51200)`

Thank you! This was exactly what I was looking for. Seems like it's caching fine now: 
![image](https://user-images.githubusercontent.com/21180505/105640542-a85b1900-5e4c-11eb-8aa9-ef9c4e959d7e.png)

**Comment by rth** [comment]
This should be resolved by https://github.com/iodide-project/pyodide/pull/1102. See https://github.com/iodide-project/pyodide/issues/240#issuecomment-775384365 for more details.
