### ISSUE TITLE
Multiple python files

### ISSUE THREAD

**Issue by MInner** [iodide-project/pyodide#419]
Hi, thank you for such an interesting project!

I was wondering how one could import one `.py` file from the other if the project consist of multiple files? For example, if one has a folder with files `foo.py` and `main.py` that has a line `import foo`, how one would make it work using pyodide? I have only seen examples of improrting js files produced from python modules via packaging script under the assumption that all the manifest files are avaliable. But what if I do not have package manifest files (setup.py, etc) and just want to import one py file from the other? If I understand correctly, one has to put the foo.py to a virtual FS first. Sources of complied js libraries mention `pyodide. _module` and `Module["FS_createPath"]` but I could not find any reference.

Would something like `pyodide._module.FS.writeFile` followed by plain `import X` work? 

https://emscripten.org/docs/api_reference/Filesystem-API.html#FS.writeFile

A short reference or a pointer to an existing example in the repo would be very helpful!

**Comment by mdboom** [comment]
In general, the path of least resistance here would be to make a Python package using the standard tools (distutils, setuptools), and then make a Pyodide package out of that using the [these docs](https://github.com/iodide-project/pyodide/blob/master/docs/new_packages.md), or putting the package on PyPI and using `micropip` to download it.

If you really just want to "create some files and import them", you can use the Python filesystem API to create them:

```
import sys
sys.path.insert(0, '.')

with open("module.py", "w") as fd:
   fd.write("foo = 42")

import module
module.foo
```

You could probably get `FS.writeFile` to work, too, if you wanted to do it from Javascript.  But I don't think anyone has gotten that to work, and it's not really considered "public API" and would be subject to change.

**Comment by rth** [comment]
Closing as resolved. Don't hesitate to comment if you have other questions.

**Comment by xhlulu** [comment]
@rth Sorry for the necro, but what's the best way to access static files from the python scope?

I have a very simple file structure like this one:
```
static/
    js/
        main.js
    py/
        main.py
        func.py
    index.html
app.py
```

Where `index.html` loads `main.js`, which itself `fetch` and run `main.py` with pyodide.

Now, if I want to import `func.py` inside `main.py`, the first thing i'd try would be:
```python
from func import my_func

my_func()

# ...
```

Obviously that didn't work for me, as only `main.js` was able to "locate" `/static/py/func.py`, but when I try to find that static file by calling `os.listdir` with pyodide, I was unable to find that file in root or any of the directories appearing there.

This is a compelling use case for me since I could build more complex python projects without having to cram everything in a single module. Otherwise I could try to use the `micropip` approach, but I would rather avoid build+publish every time I make minor changes to my project.

**Comment by rth** [comment]
You would need to get your Python files into the virtual filesystem somehow. The easiest is still loading a wheel with micropip (it doesn't need to be from PyPi, could be from your server directly).

Otherwise you would need to download your file with either fetch or `pyodide.open_url`, then write it to the virtual filesystem, and import it after adding to sys path (https://github.com/pyodide/pyodide/issues/419#issuecomment-491876403).

**Comment by MInner** [comment]
What I ended up doing was to have a server that, upon request to /app.zip zips all my python scripts, converts binary to base64 and send it as a response. On the client side I requested that address on launch and unzipped the content into the virtual file system.

**Comment by xhlulu** [comment]
Thanks for the suggestions. I was able to successfully use the `wheels` approach, but I wanted to experiment with zipping/unzipping since it doesn't depend on a `setup.py` file.

Turns out it's a bit convoluted when done from JavaScript, and took me a while to resolve it. Sharing the process here in case it's useful, which you can also find in [this repo](https://github.com/xhlulu/pyodide-multi-module-template).

----

So I updated my file structure to be the following:
![image](https://user-images.githubusercontent.com/21180505/126015636-0be1221c-b75a-4f24-a3be-6716e4114478.png)

I wanted to import `my_project` by copying it to virtual filesystem. So I updated my simple `app.py` flask app to also create an archive at the start:

```python
import shutil
from flask import Flask

shutil.make_archive("static/py", 'zip', "static/py")

app = Flask(__name__)

@app.route("/")
def hello_world():
    return app.send_static_file('index.html')


if __name__ == "__main__":
    app.run(debug=True)
```

Now whenever I boot the server, `static/py.zip` gets updated and served through my web server. So now I needed to modify my `main.js` to be following:
```js
window.bufferToString = buffer => (
    String.fromCharCode.apply(null, new Uint8Array(buffer))
);

async function main() {
    await loadPyodide({
        indexURL: "https://cdn.jsdelivr.net/pyodide/v0.17.0/full/"
    });

    const script = await fetch("/static/py/main.py");
    const scriptText = await script.text();
    pyodide.runPythonAsync(scriptText);
}

main();
```

The `bufferToString` JS function can only be defined inside the JS scope since it uses the `new` keyword. The primary function was to convert an array buffer to a JS string that can be encoded with base64.

Finally, inside `main.py`, I was able to: (1) decode the base64 file, (2) save and unzip it, (3) and import it:
```python
import base64
import os
import sys
import zipfile

import js

async def load_file(path) -> 'BytesIO':
    r = await js.fetch(path)
    buffer = await r.arrayBuffer()
    encoded = js.btoa(js.bufferToString(buffer))
    decoded = base64.b64decode(encoded)

    return decoded

decoded = await load_file('/static/py.zip')

with open('py.zip', 'wb') as f:
    f.write(decoded)

with zipfile.ZipFile('py.zip', 'r') as zip_ref:
    zip_ref.extractall()

print(os.listdir())
# => ['tmp', 'home', 'dev', 'proc', 'lib', 'py.zip', 'my_project', 'main.py']

sys.path.insert(0, '.')
import my_project

print(my_project, my_project.foo)
print(my_project.foo())
print(my_project.my_module.bar())
```

**Comment by hoodmane** [comment]
Yeah it would be great at some point to make some example repositories with suggestions for how to organize code. It takes a fair amount of work to figure out and there isn't much to go on.

**Comment by xhlulu** [comment]
@hoodmane Agree! When such repos are created, free to [re-use or modify the repo I created](https://github.com/xhlulu/pyodide-multi-module-template)!

By the way, I'm modifying the example to remove the JS `bufferToString` in favor of a Python function `buff_to_str`, so the logic would not be spread across both JS and python.

**Comment by hoodmane** [comment]
At this point probably the most efficient approach is as follows:
```
from js import fetch
pybuf = bytearray(1000)
def fetch_and_decode(url):
   jsbuf = await (await fetch(url)).arrayBuffer()
   if len(jsbuf) > len(pybuf):
      pybuf = bytearray(jsbuf)
   target_buf = pybuf[:len(pybuf)]
   jsbuf.assign_to(target_buf)
   return target_buf.decode()
```
