### ISSUE TITLE
Serving python application directly

### ISSUE THREAD

**Issue by phorward** [iodide-project/pyodide#481]
Hi everyone!

I have an application written in pure Python, which is not packaged providing a setup.py or something similar. Especially for development purposes and due to custom modifications, the application cannot always be made available via a public URL at PyPI or somewhere else.
The best way - in my opinion - would be to store my current application sources in some kind of "file system" which is then served to pyodide can directly be imported, so it behaves like a Python interpreter I locally invoke and run a python script / package from my local file system.
Regarding to #417 and #469, loading one module from a location would be possible, but the application exists of several modules.

Is such a solution possible or do you have any other suggestions how this can be solved? Always compile and building packages using a local pyodide development environment is a bad option, especially for debugging and development.

During my recent research I was unable to find any useful information on how to resolve my use case, so please be patient with me that I post it as issue here.

Thanks for any tips and help!

**Comment by rth** [comment]
> The best way - in my opinion - would be to store my current application sources in some kind of "file system" which is then served to pyodide can directly be imported, so it behaves like a Python interpreter I locally invoke and run a python script / package from my local file system.

If pyodide worked in node.js you would be able to load packages from your file-system directly. There was work done to make it happen it happen in https://github.com/iodide-project/pyodide/pull/183 (and there is a functioning implementation in https://github.com/gabrielfreire/pyodide-node, though with a somewhat outdated version now).

Otherwise, I think browser sandboxing won't allow you to interact with the filesystem, unless you are running an HTTP server on localhost.

> Always compile and building packages using a local pyodide development environment is a bad option, especially for debugging and development.

There is WIP to avoid rebuilding packages needlessly in https://github.com/iodide-project/pyodide/pull/466, that might help some.

**Comment by phorward** [comment]
I've created PR #489 and finished it now, it works perfectly for my needs!
