### ISSUE TITLE
subprocess calls fail with BlockingIO error

### ISSUE THREAD

**Issue by scopatz** [iodide-project/pyodide#548]
From the console.html example, I see the following:

```
Welcome to the Pyodide terminal emulator 🐍
>>> import subprocess
>>> subprocess.run(["echo", "hello"])
Error: Traceback (most recent call last):
  File "/lib/python3.7/site-packages/pyodide.py", line 44, in eval_code
    return eval(compile(expr, '<eval>', mode='eval'), ns, ns)
  File "<eval>", line 1, in <module>
  File "/lib/python3.7/subprocess.py", line 453, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/lib/python3.7/subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "/lib/python3.7/subprocess.py", line 1430, in _execute_child
    restore_signals, start_new_session, preexec_fn)
BlockingIOError: [Errno 11] Resource temporarily unavailable
```

**Comment by rth** [comment]
That's expected. Threading is not yet supported (https://github.com/iodide-project/pyodide/issues/237) in pyodide but could probably be made to work. 

Creating new processes is not going to be possible (in the near future or at all).  popen syscall is currently a no op in emscripten https://github.com/emscripten-core/emscripten/pull/3819 and the WASM spec has only a vague mention of it under [future features](https://github.com/WebAssembly/design/blob/master/FutureFeatures.md#multiprocess-support).

**Comment by scopatz** [comment]
OK, thanks @rth!

**Comment by mdboom** [comment]
Yep.  There are projects that aim to create something more like a proper OS in wasm, like browsix, but we're trying to avoid that level of abstraction atm.

**Comment by scopatz** [comment]
Let me know if this ever becomes available!

**Comment by marty331** [comment]
@mdboom How about now? 🤞

**Comment by MattHodgman** [comment]
Any update on when multiprocessing will be available?

**Comment by hoodmane** [comment]
The underlying support for this feature is mature enough that we could reasonably begin working on it. Firefox has supported Wasm threads since Firefox 78 released on July 28, 2020. Chrome added full support for Wasm threads in Chrome 75 released June 4, 2019. Our policy is roughly that a feature should have a full year of support in both Firefox and Chrome before we begin using it and this will be the case in a few months.

It is unclear how much time / developer effort it will take to support this, but it is a very desirable feature.

Emscripten does have the warning:

> It is not possible to build one binary that would be able to leverage multithreading when available and fall back to single threaded when not. The best you can do is two separate builds, one with and one without threads, and pick between them at runtime.

So for people wanting to support Safari they would probably need a separate build.

Seems like if we compile with `-s PROXY_TO_PTHREAD` then we may be able to address a lot of the webworker / synchronous IO woes that arise with Pyodide.

**Comment by hoodmane** [comment]
There are a pretty significant number of limitations listed here:

https://emscripten.org/docs/porting/pthreads.html

so it's hard to know how well this will work in practice. Someone will have to try it out.
