### ISSUE TITLE
Thinking Big

### ISSUE THREAD

**Issue by guettli** [iodide-project/pyodide#553]
Why do you want this?

> The Python scientific stack, compiled to WebAssembly

Why not bigger?

> Python, compiled to WebAssembly

**Comment by phorward** [comment]
Agreed, I'm with you. [Our fork](https://github.com/mausbrand/pyodide) of Pyodide is just for the pure Python we're using to write Python Apps running in the browser.

**Comment by guettli** [comment]
Is a fork the best solution? Why not work together on one repo?

**Comment by phorward** [comment]
> Is a fork the best solution? Why not work together on one repo?

This requires for a a project maintenance with a specific goal of the project, which is in your words a "Python, compiled to WebAssembly". Pyodide comes from the scientific view, where Python is used for scientific calculations and data analysis mostly.

That's the goal of the Pyodide project, and I'm very happy that this project exists and that I was able to abstract it for our use-case. This is, again, a different goal, focused on writing web-based apps  now in pure Python3. We do this together with our own [html5 abstraction library](https://github.com/viur-framework/html5/tree/pyodide) that we use throughout our open source and customer projects. Our first customer project based on Pyodide went online two weeks ago, and it runs and performs great until now! We formerly used the PyJS transpiler to achieve this goal, but PyJS was only Python 2.6 and abandoned, and Pyodide definitely performs much better.

My vision of a "Python in the browser" would be to provide a Pyodide-based Python 3.x packaged together with above html5 library and a neat CSS-tooling to build awesome, fast and integrated web-based programs, entirely running in the browser. Maybe as some kind of competitor to well-known JavaScript-based projects like Angular or React, and that's really big thinking! Further packages like the ones coming with Pyodide may be integrated from a given package repo for specific use-cases. Therefore, we decided to continue with our vision of a "Python in the browser" in a separate fork of Pyodide, apart from the scientific view, but still with connections, code sharing and pull requests between the fork and its upstream.

I think that's in the pure meaning of open source thinking: Establish a great base, and do focused forks on it.

**Comment by guettli** [comment]
Cool, this sound great. I am a bit skeptical about the initial page load. I guess this will be a bit heavy.

**Comment by mdboom** [comment]
@phorward: What are your plans for the fork?  I'd had for us to diverge and not be able to share improvements on the CPython base.  Would a feature to just extract the core Python bits out of Pyodide work for you?

**Comment by mdboom** [comment]
@guettli: Can you clarify the premise?  It seems that the "scienfitic Python stack" is a superset of "Python".  Maybe I'm missing what you're getting at?

**Comment by phorward** [comment]
> Would a feature to just extract the core Python bits out of Pyodide work for you?

Such a feature would be very helpful, but it must be configurable in a way that the packages (especially the big ones) are not built during a make run. I wasn't sure if Pyodide focuses especially on the scientific libraries, but a more general just "Python, compiled to WebAssembly" would be awesome.

> What are your plans for the fork?

Right now, the fork is mostly equal to Pyodide. But in future we plan to add some libraries and tools required especially for our web-app development purposes. I think this is OK, because we have this more specialized focus in our business.

>  I am a bit skeptical about the initial page load. I guess this will be a bit heavy.

You're right. We first concentrate on web apps that more look like real applications and focus on Desktop use.

**Comment by guettli** [comment]
@mdboom for me "Python" is bigger than "scientific Python stack". I don't do "science". I never used the scientific Python stack, and I guess I won't in the future. For me "Python" is general and  "scientific Python stack" specific. The general solution helps more people. I guess you see this different. I just wanted you to know how a person outside this scientific stack sees this.

**Comment by rth** [comment]
> I wasn't sure if Pyodide focuses especially on the scientific libraries, but a more general just "Python, compiled to WebAssembly" would be awesome.

Pyodide does focus more on the scientific stack, but the point is that to make that work you need Python in general to work first. So supporting the scientific stack is a larger and more difficult task than  supporting Python.

If you don't need the scientific stack, it would be great to render the build system more modular so that you could just skip those, when building locally, without having to maintain a separate fork. 

> But in future we plan to add some libraries and tools required especially for our web-app development purposes.    

If they are pure python, wouldn't installing those from PyPi directly work https://pyodide.readthedocs.io/en/latest/pypi.html#installing-packages-from-pypi ? Otherwise it they are popular python packages we can add them in pyodide as well.

**Comment by guettli** [comment]
> If you don't need the scientific stack, it would be great to render the build system more modular so that you could just skip those, when building locally, without having to maintain a separate fork.

This sounds good. Making things easier  for new comers is useful. If it is more modular, than people only interested in Python (without the scientific stack) can do help faster, because less things need to be understood.

**Comment by phorward** [comment]
> If you don't need the scientific stack, it would be great to render the build system more modular so that you could just skip those, when building locally, without having to maintain a separate fork.

I think that's the point of this discussion, and a good feature request! :+1:

> If they are pure python, wouldn't installing those from PyPi directly work https://pyodide.readthedocs.io/en/latest/pypi.html#installing-packages-from-pypi ? Otherwise it they are popular python packages we can add them in pyodide as well.

Right now, they are too unpopular and used in our own solutions only. Furthermore, they are currently in a state where fast modification and enhancement is required, therefore they are not compiled into packages, but imported as modules using the [remotePath feature](#489). But we're working on putting them to PyPi.

**Comment by mdboom** [comment]
@rth wrote
> Pyodide does focus more on the scientific stack, but the point is that to make that work you need Python in general to work first. So supporting the scientific stack is a larger and more difficult task than supporting Python.

Thanks, @rth -- you wrote what I was thinking better than I did.

I think it would be a very simple addition (and maybe address @phorward's use case) to have a config file at the top to select the packages you want to build.  By default, this would have `*`, but local admins could just put a short list of the packages they care about.  Selecting which packages to build is already done from Python (not a Makefile) that Pyodide "owns".

@phorward: If pyodide had such a thing, would you still need your fork?

**Comment by phorward** [comment]
> @phorward: If pyodide had such a thing, would you still need your fork?

This sounds great, and I think a fork might not be necessary in this case, when all pull requests are fine (I still need to fix the issues in #489). Please don't panic with my mention of the fork, Pyodide will remain the upstream for all diverging things we might do. It's just because some features may not be usable for some people or are experimental.

**Comment by guettli** [comment]
I guess it would be too much work for you to split pyodide into two git repos: One for the general Python part, and one for the scientifc part which build upon the generic part.

**Comment by mdboom** [comment]
> I guess it would be too much work for you to split pyodide into two git repos: One for the general Python part, and one for the scientifc part which build upon the generic part.

Yeah -- I think that would add a lot of release and build complexity for little gain.  The distribution pyodide produces has had this division since day one -- it's completely normal/reasonable to use the Python part on its own without any overhead from the Scipy stack.  I think all we would need to do is turn off the packages in the build for those that don't need them.

**Comment by phorward** [comment]
Hi there, here's a pleasant status update on this issue. I now entirely moved away from the idea of "forking" Pyodide to a "minimized version", and [our software](https://github.com/viur-framework/viur-vi) is now using the officially built packages from here, using a simple setup script called [get-pyodide.py](https://github.com/viur-framework/viur-vi/blob/master/get-pyodide.py) now.

**Comment by mdboom** [comment]
Thanks for the update, @phorward. Indeed, that looks like a simple solution!
