### ISSUE TITLE
Building just few custom package

### ISSUE THREAD

**Issue by filips123** [iodide-project/pyodide#579]
Is it possible to build just a few additional custom packages, without building the whole Pyodide again, and then using it with existing Pyodide build?

I'm not talking about usage with Iodide, but with a custom website which uses Pyodide from Github Releases or CDN.

**Comment by rth** [comment]
It should be possible, and very useful, but the corresponding feature hasn't been implemented yet.

See https://github.com/iodide-project/pyodide/issues/553#issuecomment-555480086 it shouldn't be too difficult to add. Would you like to make a PR?

**Comment by filips123** [comment]
Yes, I can maybe create PR. Can you provide a few more details what should be done?

**Comment by rth** [comment]
You would still need to build CPython in any case, but in [buildall.py:build_packages](https://github.com/iodide-project/pyodide/blob/master/pyodide_build/buildall.py#L31) instead of building all the packages, select only a subset of those (that should still satisfy dependencies). 

That python script is called from the main `Makefile` via [`packages/Makefile`](https://github.com/iodide-project/pyodide/blob/49bcd6759e31075cbbb68fa51847b9660cb60ed0/packages/Makefile#L5).
So one can imagine reading a config file from that makefile and building only a subset of packages as specified. We still need to use makefiles as those setup all the ENV variables used for the build.

**Comment by filips123** [comment]
Would it be possible to use pre-built CPython?

So basically, `packages/Makefile` needs to read list of packages (list could be contained in `Makefile.envs`) and then forward it to `buildall.py:build_packages` which should exclude packages that are not listed in list? If so, I can do this today or tomorrow.

**Comment by rth** [comment]
Closing as resolved cf https://pyodide.readthedocs.io/en/latest/building_from_sources.html#partial-builds

> Would it be possible to use pre-built CPython?

Yes, there is https://github.com/iodide-project/pyodide/issues/656 about it.
