### ISSUE TITLE
Need CORS headers on pyodide-cdn2

### ISSUE THREAD

**Issue by wlach** [iodide-project/pyodide#669]
Seeing this when I try to load pyodide from iodide:

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://pyodide-cdn2.iodide.io/v0.15.0/full/pyodide.js. (Reason: CORS header “Access-Control-Allow-Origin” missing).`

@rth can you enable this on the s3 bucket? According to [cloudflare's documentation](https://support.cloudflare.com/hc/en-us/articles/200308847-Using-cross-origin-resource-sharing-CORS-with-Cloudflare) it should respect the setting when proxying.

**Comment by rth** [comment]
Hmm, it should be enabled in S3. There is currently the following setup,
```xml
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
</CORSRule>
</CORSConfiguration>
```
I'm also able to run the https://pyodide.readthedocs.io/en/latest/using_pyodide_from_javascript.html#complete-example on a remote server, which shouldn't be possible without CORS I though? 

But you are right that I don't see CORS headers,

<details>

```
http GET https://pyodide-cdn2.iodide.io/v0.15.0/full/pyodide.js -d
HTTP/1.1 200 OK
Accept-Ranges: bytes
Age: 1134
CF-Cache-Status: HIT
CF-RAY: 59692a237dd80818-CDG
Cache-Control: max-age=30758400
Connection: keep-alive
Content-Length: 15468
Content-Type: application/javascript
Date: Wed, 20 May 2020 21:31:26 GMT
ETag: "db8c328c6ffd2d78013f4d285c8b8ecc"
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Last-Modified: Wed, 20 May 2020 20:15:33 GMT
Server: cloudflare
Set-Cookie: __cfduid=d7478a20338c1b58a312542e7568b80861590010286; expires=Fri, 19-Jun-20 21:31:26 GMT; path=/; domain=.iodide.io; HttpOnly; SameSite=Lax; Secure
Vary: Accept-Encoding
cf-request-id: 02d598aa2f00000818a8901200000001
x-amz-id-2: 5zCOoT8ZSBin70f9a/PxlVWKzk7IYv5xhUFKncHRDH1MFjT82kyl5HWTKnLaEVM3AGi8aDEuNww=
x-amz-request-id: A4A00B55FF0658C7
```

</details>

will investigate more.

**Comment by rth** [comment]
@wlach Could you try with,
```html
<script src="https://pyodide-cdn2.iodide.io/v0.15.0/full/pyodide.js" crossorigin=""></script>
```
that does return a "Access-Control-Allow-Origin" header. Though the issue is then for loading all the packages. Apparently it only responds with a CORS headers if there is an `Origin` header in the request,

> Verify that the request has the Origin header.
> If the header is missing, S3 doesn't treat the request as a cross-origin request, and doesn't send CORS response headers in the response.

Is it can we do something to include this header in requests?

**Comment by rth** [comment]
https://stackoverflow.com/a/34786878/1791279 might be a solution.

**Comment by wlach** [comment]
Hmm, I think adding it to the header in the requests should be a last
resort, as it's a bit of a gotcha for any user of pyodide (aside from the
package problem you mention). I'd prefer to exhaust the other possibilities
first.

**Comment by wlach** [comment]
This stackoverflow post has varying answers that seem worth trying, in
particular this one: https://stackoverflow.com/a/46912800

**Comment by rth** [comment]
> This stackoverflow post has varying answers that seem worth trying

Tried that but saw no effect even bypassing Cloudflare.

> I'd prefer to exhaust the other possibilities first.

Fundamentally though, as far as I understand the `Origin` header should be set by the browser when accessing a resource on another domain. For instance, when using the https://pyodide.readthedocs.io/en/latest/using_pyodide_from_javascript.html#complete-example example, it works fine because this header is  set. The fact that it isn't set is an issue.

 For instance, https://stackoverflow.com/a/34496683/1791279 outlines some interaction between caching and Ajax that could lead to it.

**Comment by wlach** [comment]
Wait, I see what the problem is! 

We were already setting the header correctly (at least with the fetch call in iodide). If I change the URL to `https://pyodide-cdn2.iodide.io/v0.15.0/full/pyodide.js` it works fine, it's `https://pyodide-cdn2.iodide.io/latest/full/pyodide.js` that doesn't work because of the 301-- on the redirected request, it resets the origin to "null". 

<img width="1473" alt="Screen Shot 2020-05-20 at 7 04 24 PM" src="https://user-images.githubusercontent.com/20569/82506021-bc37c980-9acc-11ea-9b2d-760ac07bc4ca.png">

Two options that I can think of:

1. Somehow preserve the headers when redirecting (not sure how to do that: googling "origin null 301 fetch cloudflare" returns some promising results but it looks like their Q&A site is down)
2. Figure out how to serve the resources from /latest/ without redirecting (I guess we could just make a copy?)

**Comment by rth** [comment]
> Somehow preserve the headers when redirecting

As far as I understood setting origin to `null` when redirecting is part of the spec for security reasons. But there might indeed be more workarounds. Haven't found any so far.

> Figure out how to serve the resources from /latest/ without redirecting (I guess we could just make a copy?)

We can make a copy of the latest release at `/latest/` the problem is how to handle caching in that case. Having versioned URLs mean we can cache for long duration (currently 1 year) both in the CDN and the browser. With a non versionned URL that doesn't redirect we can't do that, and say if we set it to 1 day (to get new versions in a reasonable time) that still means that everything needs to be re-downloaded each day (including to update the CDN cache). We can do it if there is no other way, but it is not ideal.

That's the reason I put the versionned URL in the docs everywhere. For iodide as far as I understand the issue is that we don't want to make a new release for each pyodide release (and change the version number), right? 

One use-case that works well with the latest path is https://pyodide-cdn2.iodide.io/latest/full/console.html as it doesn't run into those CORS issues.

I guess we could also add some JS script that follow the redirect and then explicitly re-loads the final URL with the correct headers, but that sounds hacky.

**Comment by wlach** [comment]
Thinking about this more, maybe the right thing is to just get iodide to look up the latest version, then explicitly fetch that. I think this should be possible, I'll give it a try later today.

**Comment by rth** [comment]
We can also put JSON with the list of all available versions in the root folder (e.g. `pyodide-cdn2.iodide.io/index.json`) if that helps. Though it would take some changes to auto-generate it.

**Comment by wlach** [comment]
> We can also put JSON with the list of all available versions in the root folder (e.g. `pyodide-cdn2.iodide.io/index.json`) if that helps. Though it would take some changes to auto-generate it.

After a bunch of futzing around, I don't think there's a way to make this work transparently. Redirects don't reveal the true location per the spec (https://github.com/whatwg/fetch/issues/763)

mdboom wrote up a great proposal for iodide plugins which I think would be good for this case, but that would be a big effort. I think for now I'm just going to make iodide explicitly fetch v0.15.0 and bump the version manually when needed. It's not *that* much work (certainly less than what I've spent researching this topic so far 😄 )

I don't think there's anything more actionable to do here, feel free to close this for now.

**Comment by rth** [comment]
Yes, I also learned more about CORS than I wanted to know :)

I can help with bumping the URL in pyoide when there are new pyodide releases..
Let's keep it open in case someone does come up with an easier solution.

**Comment by cameronweibel** [comment]
I am trying the code demo listed [here](https://pyodide.readthedocs.io/en/latest/using_pyodide_from_javascript.html):
```
<!DOCTYPE html>
<html>
  <head>
      <script type="text/javascript">
          // set the pyodide files URL (packages.json, pyodide.asm.data etc)
          window.languagePluginUrl = 'https://pyodide-cdn2.iodide.io/v0.15.0/full/';
      </script>
      <script src="https://pyodide-cdn2.iodide.io/v0.15.0/full/pyodide.js"></script>
  </head>
  <body>
    Pyodide test page <br>
    Open your browser console to see pyodide output
    <script type="text/javascript">
          languagePluginLoader.then(function () {
              console.log(pyodide.runPython(`
                  import sys
                  sys.version
              `));
              console.log(pyodide.runPython('print(1 + 2)'));
          });
    </script>
  </body>
</html>
```
and I am receiving a CORS error in Chrome (Version 84.0.4147.125):
![image](https://user-images.githubusercontent.com/8155129/90251729-8a6d9f00-de3e-11ea-9ef0-7813de284586.png)

Is there a workaround for this?

**Comment by rth** [comment]
@cameronweibel you need serve those files with a local web-server https://pyodide.readthedocs.io/en/latest/using_pyodide_from_javascript.html#serving-pyodide-files as otherwise the CORS restrictions seems to be different.

`python -m http.server` might be enough if you are loading pyodide assets from the CDN.

**Comment by cameronweibel** [comment]
I tried to serve the .js file, but I was missing the .asm files from the git clone. I am still building the files now from a Docker container (it has been 12h+ so far). Is it possible to get the .asm files directly like in this [post](https://github.com/wi11yp/pyodide/pull/1/files) a while ago? 

Thank you for your help.

**Comment by rth** [comment]
> I am still building the files now from a Docker container (it has been 12h+ so far).

You should use the [`PYODIDE_BUILD` env variable](https://pyodide.readthedocs.io/en/latest/building_from_sources.html#partial-builds) to only build packages that you need.

> Is it possible to get the .asm files directly like in this post a while ago?

Yes, sure you can also download them from [Github releases](https://github.com/iodide-project/pyodide/releases/tag/0.15.0).

**Comment by cameronweibel** [comment]
Thank you! It is working now.
