### ISSUE TITLE
Firefox 79+ blocking pyodide CDN

### ISSUE THREAD

**Issue by rth** [iodide-project/pyodide#751]
This would need to be investigated more, but at least for me, I can't loads pyodide packages on Firefox 79+ with "Enhanced tracking protection" enabled. Both when using the console hosted on the CDN and using a local HTML page with remote pyodide assets on the CDN.

We don't seem to be in the [blacklist](https://github.com/mozilla-services/shavar-prod-lists/blob/79.0/disconnect-blacklist.json) but maybe there are some additional regexp, not sure. It might be worth opening an issue at https://bugzilla.mozilla.org 

**Edit:** it might also be something about my browser configuration or plugins. It also seems to happen only from time to time, whether the tracking protection is on or off. So it would be good to see if someone else also encounters the same issue.

**Comment by rth** [comment]
@albertas did you experience the same issue then? I would be good to have a confirmation, as so far I'm not sure if it's a real issue or just some side effect of my browser plugin configuration..

**Comment by albertas** [comment]
@rth I could not reproduce your problem. Just enabled Strict Enhanced Tracking Protection on Firefox 79 and pyodide works fine for me.

I had Cross-Origin Resource Sharing (CORS) problems including pyodide.js to my webpage, because somehow I ended up using a wrong source: https://pyodide-cdn2.iodide.io/v0.15.0/full/pyodide.js, instead of a recommended one: https://pyodide.cdn.iodide.io/pyodide.js. The difference between these two sources is that https://pyodide.cdn.iodide.io/pyodide.js has 'Access-Control-Allow-Origin': '*' header, and the other one does not.

**Comment by albertas** [comment]
@rth I am not sure what have changed, but I started getting this error, when trying to include https://pyodide.cdn.iodide.io/pyodide.js in my website:

`The resource from “https://pyodide.cdn.iodide.io/pyodide.js” was blocked due to MIME type
(“text/plain”) mismatch (X-Content-Type-Options: nosniff).`
