### ISSUE TITLE
CDN issue - not secure cdn & not found cdn2 versioning

### ISSUE THREAD

**Issue by lung2008123** [iodide-project/pyodide#760]
CDNs for pyodide are somehow problematic from approximately last weekend:

**Problem**

(sunsetting) CDN URLs under `https://pyodide.cdn.iodide.io/` are all not secure:

*NET::ERR_CERT_COMMON_NAME_INVALID*
[https://pyodide.cdn.iodide.io/pyodide.asm.data.js](https://pyodide.cdn.iodide.io/pyodide.asm.data.js)
[https://pyodide.cdn.iodide.io/pyodide.asm.wasm](https://pyodide.cdn.iodide.io/pyodide.asm.wasm)

CDN-2 URLs under `https://pyodide-cdn2.iodide.io/` does not support versioning as described in v0.15.0 Release notes:

*working*
[https://pyodide-cdn2.iodide.io/v0.15.0/full/pyodide.js](https://pyodide-cdn2.iodide.io/v0.15.0/full/pyodide.js)

*404 Not Found*
[https://pyodide-cdn2.iodide.io/v0.14.3/full/pyodide.js](https://pyodide-cdn2.iodide.io/v0.14.3/full/pyodide.js)
[https://pyodide-cdn2.iodide.io/v0.14.0/full/pyodide.js](https://pyodide-cdn2.iodide.io/v0.14.0/full/pyodide.js)

**Extra Problem**

pyodide demo on iodide is blocked by CORS policy:

[https://alpha.iodide.io/notebooks/300/](https://alpha.iodide.io/notebooks/300/)

**Replicate Problem**

1. Go to the URL, either via browser or programmatically 

2. Run and execute the iodide notebook

p.s. Thanks for the amazing project you created! Really helps a lot in promoting Python & coding in general!

**Comment by rth** [comment]
Thanks for opening this issue @lung2008123 !

> (sunsetting) CDN URLs under https://pyodide.cdn.iodide.io/ are all not secure:

Yes, we sunset the previous URL a week ago or so, hoping there weren't too many users relying on it. So that URL will no longer work, and the way it show on netlify is with this SSL error apparently.

> CDN-2 URLs under https://pyodide-cdn2.iodide.io/ does not support versioning as described in v0.15.0
> 404 Not Found
> pyodide-cdn2.iodide.io/v0.14.3/full/pyodide.js

The idea is that this URL will contain versions 0.15.0 and later. Do you absolutely require 0.14.3? We could add it, but the issue is that at the moment we have around 300 GB/month in downloads on the new CDN (which translates into some cost), and this is likely to increase the more versions we add. We are looking into other CDN providers at the moment, which should improve this situation (transparently to users).

> pyodide demo on iodide is blocked by CORS policy:

I just tried that link in Firefox and Chrome and I can't reproduce this issue. There was an earlier related discussion in https://github.com/iodide-project/pyodide/issues/669

**Comment by lung2008123** [comment]
@rth appreciate for your reply!

> ...hoping there weren't too many users relying on it.

We changed the sunsetting CDN URLs to updated ones, just a click right away. But the way the old users get to know this permanent shutdown of CDN is to occur cannot-load-error like us in the first place. For a smoother transition, would the team consider redirect or a sunset note to all?

> The idea is that this URL will contain versions 0.15.0 and later.

Now I get the idea! Just a minor wording misunderstanding: `supports versioning` in v0.15.0 documentation gave me an idea that I could access all versions via the new CDN URL; `supports versioning from v0.15.0` would be much clearer!

> Do you absolutely require 0.14.3?

No. Would be nice to save the budget on anything but not old versions CDN. I misunderstood `versioning` as described above. `git clone` would do the job!

> pyodide demo on iodide is blocked by CORS policy:

Tricky, now it runs perfectly and not an issue anymore.

(off topic) I see multiple ecommerce website in production had failed for CORS policy in recent 2 months; might be a CORS policy violation spike? lol

**Comment by smkm** [comment]
> We are looking into other CDN providers at the moment, which should improve this situation (transparently to users).

As I have shown such concern before, CDN addresses should be consistent.

https://www.keycdn.com/open-source-cdn

These guys could or could not give a customized deploy configuration to Pyodide with whatever backend you used for the current CDN if you guys email them. Could be easiest but least open-sourced.

https://github.com/cdnjs/packages/blob/master/CONTRIBUTING.md

If you guys make Pyodide into an NPM package, this could be a viable and open-source option too (sufficient popularity, etc.). But if an NPM package is available, JSDelivr also works without specific registration.

https://www.jsdelivr.com/?docs=gh

JSDelivr claims to support releases too so that it doesn't contribute to repo size.

```
// load any GitHub release, commit, or branch

// note: we recommend using npm for projects that support it

https://cdn.jsdelivr.net/gh/user/repo@version/file
```

https://github.com/jsdelivr/jsdelivr#custom-cdn-hosting

```
We can work together and setup a custom configuration for your project. This way, you can have full control over your files and the ability to utilize the full power of jsDelivr.

This kind of custom hosting can be suitable for:

Binary hosting. Windows executable files and zips.
Frequently updated files.
Projects that can't follow jsDelivr file structure.
Some other use that will blow all of our minds.
Simply send an email to dak@prospectone.io with a request for more information.

Current OSS projects using custom configs:

webjars
webpack webpackbin and codesandbox
```
They also claim to do custom hosting based on whatever the current CDN backend is.

A CDN doesn't suffice by relying on one interface. Try deploying in 2 or more services.
