### ISSUE TITLE
Nested attribute access in JS->Python type conversion

### ISSUE THREAD

**Issue by rth** [iodide-project/pyodide#788]
Currently the following code fails,
```js
>>> from js import window
>>> window.URL.createObjectURL
Error: Traceback (most recent call last):
  File "/lib/python3.7/site-packages/pyodide.py", line 45, in eval_code
    return eval(compile(expr, '<eval>', mode='eval'), ns, ns)
  File "<eval>", line 1, in <module>
AttributeError: 'JsBoundMethod' object has no attribute 'createObjectURL'
```
(while `window.URL.createObjectURL` is a valid JS object) because nested attributes (i.e. attribute of an attribute) don't seem to be supported. It would have been nice to make it work, though I have not looked at how difficult that would be.

**Comment by hoodmane** [comment]
Ah this is another issue with the typeconversions code! I'll try to fix it.

**Comment by hoodmane** [comment]
The issue here is a bad interaction between `pyproxy.c` and `jsproxy.c`. In particular, if you index a `jsproxy` and the value of the field  is a `pyproxy` then instead of returning the wrapped python object `jsproxy` returns a `JsBoundMethod`. It does this because the `pyproxy` is a function. Why is it a function? Well it might implement `__call__` and javascript throws an error if you try to call something that is not a function. So the `PyProxy` is a function.
https://github.com/iodide-project/pyodide/blob/41592637e6a5231d1fa74235ec5f46919c18e25d/src/type_conversion/pyproxy.c#L144

Then `JsProxy` should check first whether the function is a `PyProxy` or not before just blindly returning a `JsBoundMethod`.
https://github.com/iodide-project/pyodide/blob/master/src/type_conversion/jsproxy.c#L70

I can submit a PR to fix this, though this is code that I plan to rewrite much more drastically soon.
