### ISSUE TITLE
Stdlib Support?

### ISSUE THREAD

**Issue by chrisspen** [iodide-project/pyodide#933]
How much of the standard library does Pyodide support? Can it access packages like socket/threading/multiprocessing?

**Comment by rth** [comment]
Most of the stdlib is working. You can find the removed modules in https://github.com/iodide-project/pyodide/blob/master/cpython/remove_modules.txt .

> Can it access packages like socket/threading/multiprocessing?

Those are also not working due to the limitation of the WASM VM. For more details see https://github.com/iodide-project/pyodide/issues/140, https://github.com/iodide-project/pyodide/pull/796. Threading should work once there is better browser support https://github.com/iodide-project/pyodide/issues/237

Closing this issue as answered but don't hesitate to comment here or in linked issues.
